version: "3"

services:
  yali:
    container_name: yali
    entrypoint: ["sudo", "chown", "-R", "${NONROOTUSER}", "${VOLUME}"]
    command: "./yali/Classification/Classify.sh ${MODEL} ${TRAINDATASET} ${OPTLEVEL} ${NUMCLASSES} ${TESTDATASET}"
    logging:
      driver: none
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Volume:${VOLUME}
