version: "3"

services:
  nginx:
    container_name: yacos
    image: yacos:ubuntu-20.04
    logging:
      driver: none
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Volume:/yali/Dataset
