version: "3"

services:
  nginx:
    container_name: yali
    image: yali:ubuntu-20.04
    logging:
      driver: none
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Volume:/yali/Dataset
