version: "3"

services:
  yali:
    container_name: yali
    entrypoint: "/start.sh \"${ROUNDS}\" \"${VOLUME}\" \"${MEMORYPROF}\" \"${MODEL}\" \"${TRAINDATASET}\" \"${OBF_TRAIN}\" \"${OPTLEVELTRAIN}\" \"${NUMCLASSES}\" \"${REPRESENTATION}\" \"${FILTER_HISTOGRAM}\" \"${OBF_TEST}\" \"${TESTDATASET}\" \"${OPTLEVELTEST}\""
    logging:
      driver: local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Volume:${VOLUME}
