version: "3"

services:
  yali:
    container_name: yali
    entrypoint: "/start.sh ${VOLUME} ${MODEL} ${TRAINDATASET} ${OPTLEVELTRAIN} ${NUMCLASSES} ${TESTDATASET} ${OPTLEVELTEST}"
    logging:
      driver: none
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Volume:${VOLUME}
